services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: Frontend
    ports:
      - "5173:5173"
    volumes:
    # Only mount what changes during development
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/index.html:/app/index.html
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8002
      - PROD=false
      - WATCHPACK_POLLING=true
      - VITE_HMR_HOST=localhost
    depends_on:
      - api
      - db
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: Backend
    ports:
      - "8002:8002"
    command: "uvicorn main:app --host 0.0.0.0 --port 8002 --reload"
    volumes:
      - ./backend:/app
    environment:
      PRODUCTION : false
      POSTGRES_HOST: db
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: changeme
      POSTGRES_PORT: 5432
      SUPERUSER_SECRET_TOKEN: "supersecret"
      SECRET_KEY: "SecretKey"
      SMTP_EMAIL: "internal@sudurasimontaj.com"
      SMTP_PASSWORD: "58,lANDeB,_"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      REDIS_DB: 0
    depends_on:
      - db
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: postgres:15.14-alpine3.21
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: changeme

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data


volumes:
  db-data:
  cache:
    driver: local